export const soul = {
  name: "soul-phase",
  colors: {
    background: "#e5e4e2",
    navbarBackground: "#ff8b00",
    navbarText: "#black",
    navbarBorder: "black",
    h1Header: "#ff8b00",
    pHeader: "black",
    skillsHover: "orangered",
    swiper: "#ff8b00",
    divider: "#ff8b00",
    skillsBorder: "black",
    skillsBackgroundHover: "orangered",
    skillsTextHover: "#e5e4e2",
    skillsShadow: "black",
    buttons: "#ff8b00",
    buttonsBackgroundBefore: "#e5e4e2",
    buttonsHoverBackground: "orangered",
    buttonsBorder: "#ff8b00",
    buttonsTextBefore: "#ff8b00",
    buttonsTextHover: "#e5e4e2",
    imageBorder: "orangered",
    imageBorderShadow: "orangered",
    contactButtons: "#ff8b00",
    contactButtonsHover: "orangered",
    footerBackground: "#ff8b00",
    footerBorder: "black",
    footerText: "#e5e4e2",
    footerHover: "black",
  },
};

export const reality = {
  name: "reality-phase",
  colors: {
    background: "#ffc7c7",
    navbarBackground: "#B3210D",
    navbarText: "#e5e4e2",
    navbarBorder: "black",
    h1Header: "#B3210D",
    pHeader: "black",
    skillsHover: "red",
    swiper: "#B3210D",
    divider: "#B3210D",
    skillsBorder: "black",
    skillsBackgroundHover: "red",
    skillsTextHover: "#e5e4e2",
    skillsShadow: "black",
    buttons: "#B3210D",
    buttonsBackgroundBefore: "#ffc7c7",
    buttonsHoverBackground: "red",
    buttonsBorder: "#B3210D",
    buttonsTextBefore: "#B3210D",
    buttonsTextHover: "#e5e4e2",
    imageBorder: "red",
    imageBorderShadow: "red",
    contactButtons: "#B3210D",
    contactButtonsHover: "red",
    footerBackground: "#B3210D",
    footerBorder: "black",
    footerText: "#e5e4e2",
    footerHover: "black",
  },
};

export const space = {
  name: "space-phase",
  colors: {
    background: "#76B6C4",
    navbarBackground: "#256794",
    navbarText: "#e5e4e2",
    navbarBorder: "black",
    h1Header: "#256794",
    pHeader: "black",
    skillsHover: "#266EF6",
    swiper: "#256794",
    divider: "#256794",
    skillsBorder: "black",
    skillsBackgroundHover: "#266EF6",
    skillsTextHover: "#e5e4e2",
    skillsShadow: "black",
    buttons: "#256794",
    buttonsBackgroundBefore: "#76B6C4",
    buttonsHoverBackground: "#266EF6",
    buttonsBorder: "#256794",
    buttonsTextBefore: "#256794",
    buttonsTextHover: "#e5e4e2",
    imageBorder: "#266EF6",
    imageBorderShadow: "#266EF6",
    contactButtons: "#256794",
    contactButtonsHover: "#266EF6",
    footerBackground: "#256794",
    footerBorder: "black",
    footerText: "#e5e4e2",
    footerHover: "black",
  },
};

export const power = {
  name: "power-phase",
  colors: {
    background: "#FDB3FF",
    navbarBackground: "rebeccapurple",
    navbarText: "#e5e4e2",
    navbarBorder: "black",
    h1Header: "rebeccapurple",
    pHeader: "black",
    skillsHover: "purple",
    swiper: "rebeccapurple",
    divider: "rebeccapurple",
    skillsBorder: "black",
    skillsBackgroundHover: "purple",
    skillsTextHover: "#e5e4e2",
    skillsShadow: "black",
    buttons: "rebeccapurple",
    buttonsBackgroundBefore: "#FDB3FF",
    buttonsHoverBackground: "purple",
    buttonsBorder: "rebeccapurple",
    buttonsTextBefore: "rebeccapurple",
    buttonsTextHover: "#e5e4e2",
    imageBorder: "purple",
    imageBorderShadow: "purple",
    contactButtons: "rebeccapurple",
    contactButtonsHover: "purple",
    footerBackground: "rebeccapurple",
    footerBorder: "black",
    footerText: "#e5e4e2",
    footerHover: "black",
  },
};

export const time = {
  name: "time-phase",
  colors: {
    background: "#abffc1",
    navbarBackground: "#006B3C",
    navbarText: "#e5e4e2",
    navbarBorder: "black",
    h1Header: "#006B3C",
    pHeader: "black",
    skillsHover: "green",
    swiper: "#006B3C",
    divider: "#006B3C",
    skillsBorder: "black",
    skillsBackgroundHover: "green",
    skillsTextHover: "#e5e4e2",
    skillsShadow: "black",
    buttons: "#006B3C",
    buttonsBackgroundBefore: "#abffc1",
    buttonsHoverBackground: "green",
    buttonsBorder: "#006B3C",
    buttonsTextBefore: "#006B3C",
    buttonsTextHover: "#e5e4e2",
    imageBorder: "green",
    imageBorderShadow: "green",
    contactButtons: "#006B3C",
    contactButtonsHover: "green",
    footerBackground: "#006B3C",
    footerBorder: "black",
    footerText: "#e5e4e2",
    footerHover: "black",
  },
};

export const mind = {
  name: "mind-phase",
  colors: {
    background: "black",
    navbarBackground: "#FFD300",
    navbarText: "black",
    navbarBorder: "white",
    h1Header: "#FFD300",
    pHeader: "white",
    skillsHover: "yellow",
    swiper: "#FFD300",
    divider: "#FFD300",
    skillsBorder: "white",
    skillsBorderHover: "black",
    skillsBackgroundHover: "yellow",
    skillsTextHover: "black",
    skillsShadow: "black",
    buttons: "#FFD300",
    buttonsBackgroundBefore: "black",
    buttonsHoverBackground: "yellow",
    buttonsBorder: "#FFD300",
    buttonsTextBefore: "#FFD300",
    buttonsTextHover: "black",
    imageBorder: "#FFD300",
    imageBorderShadow: "#FFD300",
    contactButtons: "#FFD300",
    contactButtonsHover: "yellow",
    footerBackground: "#FFD300",
    footerBorder: "white",
    footerText: "black",
    footerHover: "black",
  },
};
